- name: Deploy report to GitHub Pages branch
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "github-actions@github.com"
    git fetch origin
    git checkout report-branch || git checkout -b report-branch
    rm -rf allure-report/*
    mkdir -p .github/workflows
    cp ../.github/workflows/playwright.yml .github/workflows/playwright.yml
    cp -r allure-report/* .
    git add .
    git commit -m "Update Allure report"
    git push --force origin report-branch
